### ISSUE TITLE
2019 - Clean responses - Which networking vendor devices are you managing?

### ISSUE THREAD

**Issue by dgarros** [dgarros/netdevops-survey#29]

**Comment by fracaen** [comment]
Lessons learned:
We cannot ignore firewalls in the future. We need to either indicate that they should not be included in the responses, or list the major ones as pre-set options.

Clean-up done so far:
All F5 variations -> F5
Fortinet & Fortigate variations -> Fortinet
Capitalized A10
Merged HPE & Aruba -> HPE/Aruba. We should update the question next year.

L31 Decided not to merge Ruckus Brocase into Extreme Brocade since Ruckus is now Arris
L120 Removed “others.”
L143 Merged itemized Ciena platforms into Ciena

We should consider:
- Renaming Meraki into Cisco Meraki
- Maybe renaming Viptela
- Maybe merging all the unique responses into one big Others catch-all

229 - Cisco IOS/IOS XE
152 - Cisco NX-OS/ACI
140 - Juniper
113 - Cisco IOS XR
72 - Arista
64 - VMWare
50 - Amazon AWS
44 - Microsoft Azure
40 - HPE/Aruba
33 - Dell/EMC
24 - Extreme Networks (brocade)
22 - Huawei
21 - Google GCP
19 - Cumulus
18 - Palo Alto
10 - Nokia
9 - Fortinet
8 - F5
5 - Ciena
5 - Big Switch
4 - Checkpoint
4 - Meraki
4 - Cisco ASA
3 - Versa Networks
2 - Mikrotik
2 - Aerohive
2 - Alcatel
2 - Viptela
1 - Ruckus Brocade
1 - opengear
1 - Ceragon
1 - Vyatta
1 - Quanta
1 - D-Link
1 - Accedian
1 - Allot
1 - RAD ETX Series
1 - Adtran TA series
1 - Zhone
1 - RtBrick
1 - Riverbed
1 - Oracle Cloud Infrastructure
1 - Raisecom
1 - Cisco Wireless
1 - Infoblox
1 - Allied Telesis
1 - Force 10
1 - Icotera
1 - A10
1 - Silver-peak

**Comment by dgarros** [comment]
@fracaen Overall looks good to me, wasn't an easy one. 
We need to do a better job at explaining what we define by "vendor" in this question. 

What do you think about removing the vendors that are not producing networking devices per say, for example as far as I know
- Opengear is mostly doing console server
- Infoblox is mostly a software company
- RAD ETX Series is not really a network device more a converter 

Regarding your suggestions 
- Renaming Meraki into Cisco Meraki > Sounds good to me
- Maybe renaming Viptela > Sounds good to me
-  Maybe merging all the unique responses into one big Others catch-all > I would keep it as it in the TSV and group them in the report/graph

**Comment by fracaen** [comment]
@dgarros My initial reaction was "yes, let's remove non-network vendors". Then I went to opengear's web site and found this:
https://opengear.com/solution/NetOps-Automation-Platform
And I know other players in this space are doing more netdevops stuff. WTI has an Ansible module.
So... I don't know... I'm leaning towards leaving them in this year in the raw data, filtering them out from graphs and reports (like every other one-off), and like you said narrowing down the question for 2020.

Meraki -> Cisco Meraki
Viptela left unchanged for now. Will consider listing it under an existing Cisco response for 2020.

**Comment by dgarros** [comment]
sounds good thanks
