### ISSUE TITLE
2019 Clean responses - On the server side, what automation tools are you using ?

### ISSUE THREAD

**Issue by dgarros** [dgarros/netdevops-survey#31]

**Comment by fracaen** [comment]
@dgarros  We have a major issue with this question. A large number of respondents misunderstood what we were asking.
Instead of answering "What automation tools do you use to manage servers?", they answered "What is the server side of your network automation".

It's relatively easy to weed out some of the obviously irrelevant responses. Cisco DNA Center does not manage servers. However, some are less obvious to weed out. Nornir? Stackstorm? Can you do at least basic management of servers with those? I don't know.

And more importantly, even after we clean things up, how much can we trust the remaining responses? Of the 196 Ansible responses, how many are actually Ansible for servers versus Ansible as server managing networks?

Should we just scrap this question for 2019, and rephrase it in depth for 2020? 

196 - Ansible
45 - SaltStack
33 - Puppet
32 - We don't have automation for servers
25 - Vendor Specific
23 - Microsoft SCCM
14 - Chef
12 - RunDeck
3 - Nornir
3 - CF Engine
3 - Terraform
3 - NSO
2 - terraform
2 - StackStorm
2 - Home grown
1 - In house tooling
1 - in-house solutions
1 - Nornir/Python
1 - Stackstorn
1 - Cisco Prime and Aruba Airwave
1 - homegrown Python frameworks
1 - Home grown and sysrepo (NETCONF /YANG for servers etc)
1 - PyEZ
1 - HBEz
1 - git
1 - Robot framework
1 - DNA Centre
1 - Solarwinds NCM
1 - Python Toolset
1 - Rightscale unfortunately
1 - Fabric
1 - Not sure
1 - don't work on the server side
1 - My team doesn't manage the server side of things
1 - so unknown
1 - my own little app (multithreading and python)
1 - Powershell DSC
1 - rancid + bash
1 - Gitlab-runner
1 - PowerShell
1 - Home grown tooling
