### ISSUE TITLE
2019 Clean responses - what data sources are you using to detect problems in your network ?

### ISSUE THREAD

**Issue by dgarros** [dgarros/netdevops-survey#36]

**Comment by fracaen** [comment]
@dgarros We have 2 ThousandEyes responses. Should these be merged into External probes (pingmesh)?

L5 "Python app tester probes that perform TCP/UDP pings and traceroutes" already covered by ICMP/PING
L82 removed "not sure, not our team"
L115 NETCONF -> API. I doube the respondent is using it for streaming telemetry without selecting that.
L125 removed "custom developed apps to test the network" since other mechanisms were already listed
L207 removed "Neighbor information" redundant with routing information
L231 removed "none"

203 - SNMP
184 - ICMP/PING
179 - Syslog
111 - sFlow/Netflow
80 - Routing Information
68 - Other active probes (IP SLA/RPM)
48 - API
47 - Streaming Telemetry
26 - External probes (pingmesh)
2 - ThousandEyes
1 - Infoblox NetMRI

**Comment by dgarros** [comment]
@fracaen regarding ThousandEyes, I would say Yes. they should be part of `External probes`
